services:
  solven-api:
    container_name: solven-api
    restart: always
    image: node:20.10.0
    ports: 
     - 4007:3007
    volumes:
     - ./:/usr/src/solven
    working_dir: /usr/src/solven

    networks:
      - monorepo-network

    # FOR_PRODUCTION
    command: bash -c "rm -rf dist && npm install && npm run build && npm run start:prod"

  solven-batch:
    container_name: solven-batch
    restart: unless-stopped
    image: node:20.10.0
    ports: 
     - 4008:3008
    volumes:
     - ./:/usr/src/solven
    working_dir: /usr/src/solven

    networks:
      - monorepo-network

    # FOR_PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod:batch"


networks:
  monorepo-network:
    driver: bridge




  # solven-next: localhost: 4006 => container: 3006
  # solven-api: localhost: 4007 => container: 3007
  # solven-batch: localhost: 4008 => container: 3008    

  # docker compose up -d
  # docker compose start
  # docker compose restart
  # docker compose stop && docker compose rm -f
  # docker compose config